In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv("Project-02 Ecommerce_sales_dataset_15000_rows.csv")

In [3]:
df.shape

(15000, 12)

In [4]:
df.head()

,Order_ID,Order_Date,Customer_ID,Product_Category,Product_Name,State,City,Payment_Mode,Quantity,Sales_Amount,Discount,Profit
0,ORD100000,11-07-2023,CUST8187,Home & Kitchen,Air Fryer,Uttar Pradesh,Chennai,Cash on Delivery,5,1225,0.11,213.18
1,ORD100001,28-06-2023,CUST8470,Electronics,Laptop,Rajasthan,Ahmedabad,Credit Card,3,2355,0.21,312.75
2,ORD100002,08-01-2024,CUST3542,Electronics,Camera,Uttar Pradesh,Jaipur,Debit Card,4,1948,0.29,118.10
3,ORD100003,28-06-2023,CUST8975,Electronics,Camera,Rajasthan,Bangalore,Credit Card,1,1438,0.17,284.36
4,ORD100004,05-03-2024,CUST3112,Beauty,Hair Dryer,Rajasthan,Chennai,Net Banking,1,727,0.07,124.67

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          15000 non-null  object
 1   Order_Date        15000 non-null  object
 2   Customer_ID       15000 non-null  object
 3   Product_Category  15000 non-null  object
 4   Product_Name      15000 non-null  object
 5   State             15000 non-null  object
 6   City              15000 non-null  object
 7   Payment_Mode      15000 non-null  object
 8   Quantity          15000 non-null  int64
 9   Sales_Amount      15000 non-null  int64
 10  Discount          15000 non-null  float64
 11  Profit            15000 non-null  float64
dtypes: float64(2), int64(2), object(8)
memory usage: 1.4+ MB

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [7]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category',
       'product_name', 'state', 'city', 'payment_mode', 'quantity',
       'sales_amount', 'discount', 'profit'],
      dtype='object')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
product_name        0
state               0
city                0
payment_mode        0
quantity            0
sales_amount        0
discount            0
profit              0
dtype: int64

In [12]:
df.dtypes

order_id             object
order_date           object
customer_id          object
product_category     object
product_name         object
state                object
city                 object
payment_mode         object
quantity              int64
sales_amount          int64
discount            float64
profit              float64
dtype: object

In [13]:
df['order_date'].head()

0    11-07-2023
1    28-06-2023
2    08-01-2024
3    28-06-2023
4    05-03-2024
Name: order_date, dtype: object

In [14]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=True
)

In [16]:
df['order_date'].dtype

dtype('<M8[ns]')

In [18]:
df['quantity'] = pd.to_numeric(df['quantity'])
df['sales_amount'] = pd.to_numeric(df['sales_amount'])
df['discount'] = pd.to_numeric(df['discount'])
df['profit'] = pd.to_numeric(df['profit'])

In [19]:
df.dtypes

order_id                    object
order_date          datetime64[ns]
customer_id                 object
product_category            object
product_name                object
state                       object
city                        object
payment_mode                object
quantity                     int64
sales_amount                 int64
discount                   float64
profit                     float64
dtype: object

In [20]:
df.head()

,order_id,order_date,customer_id,product_category,product_name,state,city,payment_mode,quantity,sales_amount,discount,profit
0,ORD100000,2023-07-11,CUST8187,Home & Kitchen,Air Fryer,Uttar Pradesh,Chennai,Cash on Delivery,5,1225,0.11,213.18
1,ORD100001,2023-06-28,CUST8470,Electronics,Laptop,Rajasthan,Ahmedabad,Credit Card,3,2355,0.21,312.75
2,ORD100002,2024-01-08,CUST3542,Electronics,Camera,Uttar Pradesh,Jaipur,Debit Card,4,1948,0.29,118.10
3,ORD100003,2023-06-28,CUST8975,Electronics,Camera,Rajasthan,Bangalore,Credit Card,1,1438,0.17,284.36
4,ORD100004,2024-03-05,CUST3112,Beauty,Hair Dryer,Rajasthan,Chennai,Net Banking,1,727,0.07,124.67

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          15000 non-null  object
 1   order_date        15000 non-null  datetime64[ns]
 2   customer_id       15000 non-null  object
 3   product_category  15000 non-null  object
 4   product_name      15000 non-null  object
 5   state             15000 non-null  object
 6   city              15000 non-null  object
 7   payment_mode      15000 non-null  object
 8   quantity          15000 non-null  int64
 9   sales_amount      15000 non-null  int64
 10  discount          15000 non-null  float64
 11  profit            15000 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(7)
memory usage: 1.4+ MB

In [22]:
df.describe()

,order_date,quantity,sales_amount,discount,profit
count,15000,15000.000000,15000.000000,15000.000000,15000.000000
mean,2024-01-01 04:03:38.880000,3.012733,3292.322667,0.150105,491.851406
min,2023-01-01 00:00:00,1.000000,200.000000,0.000000,12.320000
25%,2023-07-06 00:00:00,2.000000,1422.750000,0.070000,183.435000
50%,2024-01-02 00:00:00,3.000000,2736.000000,0.150000,365.285000
75%,2024-07-01 00:00:00,4.000000,4776.000000,0.220000,680.962500
max,2024-12-31 00:00:00,5.000000,10000.000000,0.300000,2484.640000
std,NaN,1.412529,2312.812147,0.086968,413.845825

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
product_name        0
state               0
city                0
payment_mode        0
quantity            0
sales_amount        0
discount            0
profit              0
dtype: int64

In [26]:
df.to_csv("ecommerce_sales_cleaned.csv", index=False)

In [27]:
# Total Sales
total_sales = df['sales_amount'].sum()
print("Total Sales:", total_sales)

Total Sales: 49384840

In [28]:
# Total Profit
total_profit = df['profit'].sum()
print("Total Profit:", total_profit)

Total Profit: 7377771.09

In [29]:
# Total Orders
total_orders = df['order_id'].nunique()
print("Total Orders:", total_orders)

Total Orders: 15000

In [30]:
# Average Discount
average_discount = df['discount'].mean()
print("Average Discount:", average_discount)

Average Discount: 0.15010533333333334

In [31]:
# Total Quantity Sold
total_quantity = df['quantity'].sum()
print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 45191

In [32]:
import mysql.connector

conn = mysql.connector.connect(
    host="127.0.0.1",
    port=3306,
    user="root",
    password='pass123'
)
print("Connected Successfully!")

Connected Successfully!

In [33]:
cursor = conn.cursor()

# Show all available databases
cursor.execute("SHOW DATABASES")

for db in cursor:
    print(db)

# Select your database
cursor.execute("USE ecom")

('ai',)
('crop_price_db',)
('data_analytics',)
('ecom',)
('hr_dashboard',)
('information_schema',)
('mysql',)
('performance_schema',)
('prime',)
('sales',)
('smartshop',)

In [34]:
import pymysql

print("PyMySQL Installed Successfully")

PyMySQL Installed Successfully

In [35]:
from sqlalchemy import create_engine

In [40]:
engine = create_engine(
    "mysql+pymysql://root:pass123@127.0.0.1:3306/ecom"
)

In [41]:
print(engine)

Engine(mysql+pymysql://root:***@127.0.0.1:3306/ecom)

In [42]:
df.to_sql(
    name="ecom_sales",
    con=engine,
    if_exists="replace",
    index=False
    
)

15000